### REGISTER
POST http://localhost:3000/register
Content-Type: application/json

{
  "name": "David",
  "email": "david@test.com",
  "password": "123456",
  "role": "user"
}

###
### LOGIN
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "david@test.com",
  "password": "123456"
}

###
### POST REPORT
POST http://localhost:3000/reports
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWY0ZTI5OGEzYTE3MzNiY2M2MzExYTQiLCJyb2xlIjoidXNlciIsInN0YXRpb25JZCI6bnVsbCwiaWF0IjoxNzc3NjY0MzE3LCJleHAiOjE3NzgyNjkxMTd9.3q4Yg7ZCVDmg1Ud9Bs6tM-Y1fvGpIif17EqswpQYZw4

{
  "stationId": "69f34449ae9895d743142614",
  "price": 650,
  "fuelAvailable": true,
  "isOpen": true,
  "queueLevel": "short"
}